### ISSUE TITLE
Support ChipGroup

### ISSUE THREAD

**Issue by michaelbukachi** [agoda-com/Kakao#194]
Are there any plans to add ChipGroup support?
Some methods that can be added for interaction are:
```
click(index: Int)
click(text: Str)
```
And some for assertions:
```
isSelected(index: Int)
isSelected(index: Str)
isSelected(index: List<Int>)
```

I am willing to work on this and submit a pull request.

**Comment by Unlimity** [comment]
Hi there! Thanks for reaching out.
Right now we don't have any plans to support that view, since we don't have a lot of time actually. But you're more than welcome to submit a PR with support of chips.
I believe we already import material design library, so it should be relatively easy to implement.

**Comment by Unlimity** [comment]
Feature has been merged. Closing this issue.
