### ISSUE TITLE
Issue with hasDrawable when ImageView is using scaleType

### ISSUE THREAD

**Issue by lucas34** [agoda-com/Kakao#232]
#### Steps to reproduce:

  1. Use latest Kakao library
  2. Create ImageView and set android:scaleType="fitXY"
  3. Try to match the drawable using hasDrawable()
  
#### Observed Results:

Test fail. Drawable are different.
  
#### Expected Results:

Not sure if in this case the test should actually pass, because if you are using scaleType=crop the final image will indeed be different from the original image.
Is there any solution to match this kind of image ?
  
#### Relevant Code:

I can provide test cases for it if required.

**Comment by Unlimity** [comment]
@lucas34 are you providing resource id to the `hasDrawable()` assertion or some custom bitmap? If the latter is correct, then you need to provide pixel perfect matching bitmap to the bitmap being output to the user in ImageView, otherwise it will not match. In case of drawable resource id all internal alterations should be repeated by Kakao before matching bitmaps.

**Comment by lucas34** [comment]
@Unlimity 
I'm providing all the images with 
```
hasDrawable(R.drawable.video_overlay)
```

**Comment by Vacxe** [comment]
@lucas34 I tried to replicate same issue on API 25 and looks like it works. But on 28+ it failed. Could u please represent issue with PR sample. It definitely help us to understand your case and move forward quickly.
