### ISSUE TITLE
Refactor current code base

### ISSUE THREAD

**Issue by Unlimity** [agoda-com/Kakao#69]
We have segregated all current code in several files, and these files are becoming really huge.
We need to separate these files. I propose following:
 - Keep each view class and it's actions and assertions interfaces in separate files
 - Move `Builders.kt` classes to `com.agoda.kakao.builder` package and separate by class name
 - Move `Matchers.kt` classes to `com.agoda.kakao.matcher` package and separate by class name
 - Create `com.agoda.kakao.action` package and put there all custom action that we have created
 - Create `com.agoda.kakao.assertion` package and put there all custom assertions that we have created

**Comment by psh** [comment]
Given that you have this issue slated for a `2.0` release, and major version changes can introduce breaking changes to an API, I went ahead and broke apart the monolithic files and first of all packaged them by layer / function (assertions, actions, views, etc) as you suggest, albeit with slightly different naming.  [commit](https://github.com/psh/Kakao/commit/e199233b5f9b42e706432fb4612fddef2a16ea2a)

The end result was reasonable but I felt that the code would benefit from packaging by _feature_ rather than by _layer_ which is how my fork of the code stands today.  The individual packages seem to nicely encapsulate each component pulling in the view, assertions, builder and actions into one spot to give me context to see what is going on.  [commit](https://github.com/psh/Kakao/commit/8d484dc4c197018766604238080607bddd44279f)

I'd be happy to drop you a pull request with the code if you're interested!

**Comment by Unlimity** [comment]
@psh we are more than interested in any contribution. So drop your PR and let's review! Maybe this is what we need to kickoff 2.0 and move to AndroidX support libs as well.

**Comment by Unlimity** [comment]
Finally closed!
